# Generated by Django 2.2.8 on 2023-08-10 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0072_auto_20230810_0139'),
        ('platforms', '0009_auto_20230608_1322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geographicextend',
            options={'verbose_name': 'Geographic extent', 'verbose_name_plural': 'Geographic extents'},
        ),
        migrations.AlterModelOptions(
            name='platform',
            options={'verbose_name': 'Program', 'verbose_name_plural': 'Programmes'},
        ),
        migrations.RemoveField(
            model_name='platform',
            name='geographicExtend',
        ),
        migrations.AddField(
            model_name='platform',
            name='approved',
            field=models.BooleanField(null=True, verbose_name='Approved'),
        ),
        migrations.AddField(
            model_name='platform',
            name='contactPhone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telephone'),
        ),
        migrations.AddField(
            model_name='platform',
            name='qualification',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Qualification Required'),
        ),
        migrations.AddField(
            model_name='platform',
            name='topic',
            field=models.ManyToManyField(blank=True, to='projects.Topic', verbose_name='Topic'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='active',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
