# Generated by Django 2.2.8 on 2023-08-10 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20230405_2043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'ordering': ('-id',), 'verbose_name': 'Subscriber', 'verbose_name_plural': 'Subscribers'},
        ),
    ]
