# Generated by Django 3.2.25 on 2025-01-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_auto_20230810_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('pt-br', 'Brazilian Portuguese'), ('es', 'Spanish'), ('en', 'English')], default='pt-br', max_length=5, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='profile',
            name='lattes_id',
            field=models.CharField(blank=True, help_text='If you have registered on the Lattes platform, you may add your Lattes iD, to link this profile with your professional information such as affiliations, grants and publications.', max_length=16, null=True, verbose_name='Lattes ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='orcid',
            field=models.CharField(blank=True, help_text='If you have registered on the ORCID platform for researchers, you may add your persistent digital identifier, or ORCID iD, to link this profile with your professional information such as affiliations, grants, publications, peer review, and more.', max_length=50, null=True, verbose_name='ORCID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profileVisible',
            field=models.BooleanField(default=False, verbose_name='Profile visible'),
        ),
    ]
